<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implement hook_theme().
 */
function senior_portal_theme($existing, $type, $theme, $path) {
  return [
    'senior_portal_page' => [
      'variables' => [
        'items' => [],
      ],
      'template' => 'senior-portal-page',
    ]
  ];
}


/**
 * Implements hook_form_alter().
 * 
 * In this form alter, we've added a new Markup field on the form (node_article_form).
 * To verify, Go to Content > Add Content > Article.
 * We can do more in hook_form_alter. But, for the test, I simply display a message.
 */
function senior_portal_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_article_form') {

    $form['senior_portal_notice'] = [
      '#type' => 'markup',
      '#markup' => '
        <div class="messages messages--status">
          Senior Portal integration enabled.
        </div>',
      '#weight' => -10,
    ];

  }
}

/**
 * Implements hook_entity_insert().
 * 
 * We can do more in hook_entity_insert, But for the test, I simply created a log once node entity has been created.
 */
function senior_portal_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() === 'node') {

    \Drupal::logger('senior_portal')->notice(
      'New node created: @title',
      [
        '@title' => $entity->label(),
      ]
    );

    \Drupal::service('cache_tags.invalidator')
      ->invalidateTags(['senior_portal:data']);

  }
}