senior_portal.settings:
  type: config_object
  label: 'Senior Portal settings'
  mapping:
    api_url:
      type: string
      label: 'API URL'

    enabled:
      type: boolean
      label: 'Enabled'